version: '3.4'
services:
  ########################
  # SERVICE DEPENDENCIES #
  ########################
  postgresql:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '35432:5432'
    volumes: 
      - ./volumes/postgresql:/var/lib/postgresql/data
networks:
  default:
