version: '3.4'
services:
  ########################
  # SERVICE DEPENDENCIES #
  ########################
  mariadb:
    image: mariadb:10.3.10
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mengajionline
      - MYSQL_USER=mengajionline
      - MYSQL_PASSWORD=mengajionline
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '--silent']
      start_period: 30s
    ports:
      - 31306:3306
    networks:
      default:
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mariadb
      - UPLOAD_LIMIT=10000000000
    ports:
      - 31080:80
networks:
  default:
